openapi: 3.0.0
tags:
  - name: Auth
  - name: Company
  - name: Employee
info:
  title: 'Gusto API [not done]'
  version: '1.0'
  termsOfService: 'https://gusto.com/about/terms'
  description: Welcome to Gusto's API documentation.
  contact:
    name: Developer Relations
    email: developer@gusto.com
servers:
  - url: 'https://api.gusto-demo.com'
    description: Demo
  - description: Production
    url: 'https://api.gusto-demo.com'
paths:
  '/v1/employees/{employee_id}':
    get:
      summary: 'Get an employee [not done]'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: number
                  version:
                    type: string
                    minLength: 1
                  first_name:
                    type: string
                    minLength: 1
                  middle_initial:
                    type: string
                    minLength: 1
                  last_name:
                    type: string
                    minLength: 1
                  company_id:
                    type: number
                  manager_id:
                    type: number
                  department:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  ssn:
                    type: string
                  date_of_birth:
                    type: string
                    minLength: 1
                  jobs:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        title:
                          type: string
                          minLength: 1
                        rate:
                          type: string
                          minLength: 1
                        payment_unit:
                          type: string
                          minLength: 1
                        location_id:
                          type: number
                      required:
                        - id
                        - title
                        - rate
                        - payment_unit
                        - location_id
                  home_address:
                    $ref: '#/components/schemas/Location'
                  garnishments:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        version:
                          type: string
                          minLength: 1
                        employee_id:
                          type: number
                        active:
                          type: boolean
                        amount:
                          type: string
                          minLength: 1
                        description:
                          type: string
                          minLength: 1
                        court_ordered:
                          type: boolean
                        times:
                          type: number
                        recurring:
                          type: boolean
                        annual_maximum: {}
                        pay_period_maximum:
                          type: string
                          minLength: 1
                        deduct_as_percentage:
                          type: boolean
                      required:
                        - id
                        - version
                        - employee_id
                        - active
                        - amount
                        - description
                        - court_ordered
                        - times
                        - recurring
                        - pay_period_maximum
                        - deduct_as_percentage
                  eligible_paid_time_off:
                    type: array
                    items:
                      type: object
                  onboarded:
                    type: boolean
                  terminated:
                    type: boolean
                  terminations:
                    type: array
                    items:
                      type: object
                  phone:
                    type: string
                    minLength: 1
                  preferred_first_name:
                    type: string
                    minLength: 1
                  work_email:
                    type: string
                    minLength: 1
                required:
                  - id
                  - version
                  - first_name
                  - middle_initial
                  - last_name
                  - company_id
                  - manager_id
                  - department
                  - email
                  - ssn
                  - date_of_birth
                  - jobs
                  - home_address
                  - garnishments
                  - eligible_paid_time_off
                  - onboarded
                  - terminated
                  - terminations
                  - phone
                  - preferred_first_name
                  - work_email
              examples:
                Employee:
                  value:
                    id: 1123581321345589
                    version: db0edd04aaac4506f7edab03ac855d56
                    first_name: Soren
                    middle_initial: A
                    last_name: Kierkegaard
                    company_id: 7757616923531095
                    manager_id: 7757869431804236
                    department: Marketing
                    email: knight0faith@example.com
                    ssn: ''
                    date_of_birth: '1990-05-05'
                    jobs:
                      - id: 1
                        title: Underwater Basket Weaver
                        rate: '80000.00'
                        payment_unit: Year
                        location_id: 3141592653589793
                    home_address:
                      id: 1402342024000
                      version: fe75bd065ff48b91c35fe8ff842f986c
                      employee_id: 1123581321345589
                      street_1: 425 2nd Street
                      street_2: Suite 602
                      city: San Francisco
                      state: CA
                      zip: '94107'
                      country: USA
                    garnishments:
                      - id: 1363316538400333
                        version: 52b7c567242cb7452e89ba2bc02cb476
                        employee_id: 8964216891236743
                        active: true
                        amount: '8.00'
                        description: Company loan to employee
                        court_ordered: false
                        times: 5
                        recurring: false
                        annual_maximum: null
                        pay_period_maximum: '100.00'
                        deduct_as_percentage: true
                    eligible_paid_time_off: []
                    onboarded: true
                    terminated: false
                    terminations: []
                    phone: '2345678901'
                    preferred_first_name: Alex
                    work_email: knight0faith@initech.biz
                Employee with multiple jobs:
                  value:
                    id: 0
                    version: string
                    first_name: string
                    middle_initial: string
                    last_name: string
                    company_id: 0
                    manager_id: 0
                    department: string
                    email: string
                    ssn: string
                    date_of_birth: string
                    jobs:
                      - id: 0
                        title: string
                        rate: string
                        payment_unit: string
                        location_id: 0
                    home_address:
                      id: 0
                      version: string
                      employee_id: 0
                      street_1: string
                      street_2: string
                      city: string
                      state: string
                      zip: string
                      country: string
                    garnishments:
                      - id: 0
                        version: string
                        employee_id: 0
                        active: true
                        amount: string
                        description: string
                        court_ordered: true
                        times: 0
                        recurring: true
                        annual_maximum: null
                        pay_period_maximum: string
                        deduct_as_percentage: true
                    eligible_paid_time_off:
                      - {}
                    onboarded: true
                    terminated: true
                    terminations:
                      - {}
                    phone: string
                    preferred_first_name: string
                    work_email: string
      operationId: get-v1-employees
      tags:
        - Employee
    post:
      summary: 'Create an employee [not done]'
      tags:
        - Employee
      operationId: post-v1-employees
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                first_name:
                  type: string
                  minLength: 1
                last_name:
                  type: string
                  minLength: 1
                email:
                  type: string
                  minLength: 1
              required:
                - first_name
                - last_name
                - email
    put:
      summary: 'Update an employee [not done]'
      tags:
        - Employee
      responses: {}
      operationId: put-v1-employees
    parameters:
      - schema:
          type: string
        name: employee_id
        in: path
        required: true
        description: The ID of the employee
  '/v1/companies/{company_id}':
    get:
      summary: Get a company
      operationId: get-v1-companies
      description: Retrieve information about a particular company.
      tags:
        - Company
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: The access token
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  ein:
                    type: string
                    description: The Federal Employer Identification Number of the company.
                    readOnly: true
                  entity_type:
                    type: string
                    description: The tax payer type of the company.
                    enum:
                      - C-Corporation
                      - S-Corporation
                      - Sole proprietor
                      - LLC
                      - LLP
                      - Limited partnership
                      - Co-ownership
                      - Association
                      - Trusteeship
                      - General partnership
                      - Joint venture
                      - Non-Profit
                    readOnly: true
                  is_suspended:
                    type: boolean
                    description: Whether or not the company is suspended in Gusto. Suspended companies may not run payroll.
                  company_status:
                    type: string
                    description: 'The status of the company in Gusto. "Approved" companies may run payroll with Gusto. "Not Approved" companies may not yet run payroll with Gusto. In order to run payroll, the company may need to complete onboarding or contact support. "Suspended" companies may not run payroll with Gusto. In order to unsuspend their account, the company must contact support.'
                    enum:
                      - Approved
                      - Not Approved
                      - Suspended
                    readOnly: true
                  id:
                    type: number
                    description: The unique identifier of the company in Gusto.
                    readOnly: true
                  name:
                    type: string
                    description: The name of the company.
                    readOnly: true
                  trade_name:
                    type: string
                    description: The trade name of the company.
                    readOnly: true
                  locations:
                    type: array
                    uniqueItems: false
                    description: The locations of the company.
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: The unique identifier of the location in Gusto.
                          readOnly: true
                        street_1:
                          type: string
                          description: ''
                          readOnly: true
                        street_2:
                          type: string
                          description: ''
                          readOnly: true
                        city:
                          type: string
                          readOnly: true
                        state:
                          type: string
                          readOnly: true
                        zip:
                          type: string
                          readOnly: true
                        country:
                          type: string
                          readOnly: true
                        active:
                          type: boolean
                          description: Whether or not the location is active.
                      readOnly: true
                    readOnly: true
                  compensations:
                    type: object
                    description: The available company-wide compensation rates for the company.
                    properties:
                      hourly:
                        type: array
                        uniqueItems: true
                        description: The available hourly compensation rates for the company.
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: The name of the hourly compensation rate.
                              example: Overtime
                              readOnly: true
                            multiple:
                              type: number
                              description: The amount multiplied by the base rate of a job to calculate compensation.
                              example: 1.5
                              readOnly: true
                          readOnly: true
                        readOnly: true
                      fixed:
                        type: array
                        uniqueItems: true
                        description: The available fixed compensation rates for the company.
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: The name of the fixed compensation.
                              example: Bonus
                          readOnly: true
                        readOnly: true
                      paid_time_off:
                        type: array
                        uniqueItems: true
                        description: The available types of paid time off for the company.
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              example: Vacation Hours
                              description: The name of the paid time off type.
                              readOnly: true
                          readOnly: true
                        readOnly: true
                    readOnly: true
                  primary_signatory:
                    type: object
                    description: The primary signatory of the company.
                    properties:
                      first_name:
                        type: string
                        readOnly: true
                      middle_initial:
                        type: string
                        readOnly: true
                      last_name:
                        type: string
                        readOnly: true
                      phone:
                        type: string
                        readOnly: true
                      email:
                        type: string
                        readOnly: true
                      home_address:
                        type: object
                        properties:
                          street_1:
                            type: string
                            readOnly: true
                          street_2:
                            type: string
                            readOnly: true
                          city:
                            type: string
                            readOnly: true
                          state:
                            type: string
                            readOnly: true
                          zip:
                            type: string
                            readOnly: true
                          country:
                            type: string
                            readOnly: true
                        readOnly: true
                    readOnly: true
                  primary_payroll_admin:
                    type: object
                    description: The primary payroll admin of the company.
                    properties:
                      first_name:
                        type: string
                        readOnly: true
                      last_name:
                        type: string
                        readOnly: true
                      phone:
                        type: string
                        readOnly: true
                      email:
                        type: string
                        readOnly: true
                    readOnly: true
              examples:
                Example:
                  value:
                    ein: 00-0000001
                    entity_type: C-Corporation
                    is_suspended: false
                    company_status: Approved
                    id: 7756341740978008
                    name: Shoppe Studios LLC
                    trade_name: Record Shoppe
                    locations:
                      - id: 7757727716657803
                        street_1: 412 Kiera Stravenue
                        street_2: Suite 391
                        city: San Francisco
                        state: CA
                        zip: '94107'
                        country: USA
                        active: true
                      - id: 7757727716657804
                        street_1: 644 Fay Vista
                        street_2: Suite 842
                        city: Richmond
                        state: VA
                        zip: '23218'
                        country: USA
                        active: true
                    compensations:
                      hourly:
                        - name: Overtime
                          multiple: 1.5
                        - name: Double overtime
                          multiple: 2
                        - name: Regular
                          multiple: 1
                        - name: Vacation
                          multiple: 1
                        - name: Outstanding vacation
                          multiple: 1
                        - name: Sick
                          multiple: 1
                        - name: Holiday
                          multiple: 1
                        - name: Emergency sick - self care
                          multiple: 1
                        - name: Emergency sick - caring for others
                          multiple: 1
                        - name: FMLA Public Health Emergency Leave
                          multiple: 1
                        - name: Regular Hours
                          multiple: 1
                      fixed:
                        - name: Bonus
                        - name: Commission
                        - name: Paycheck Tips
                        - name: Cash Tips
                        - name: Correction Payment
                        - name: Severance
                        - name: Minimum Wage Adjustment
                        - name: Reimbursement
                      paid_time_off:
                        - name: Vacation Hours
                        - name: Sick Hours
                        - name: Holiday Hours
                    primary_signatory:
                      first_name: Alda
                      middle_initial: ''
                      last_name: Carter
                      phone: 1-565-710-7558
                      email: louie.hessel7757869450111547@zemlak.biz
                      home_address:
                        street_1: 524 Roob Divide
                        street_2: Suite 565
                        city: San Francisco
                        state: CA
                        zip: '94107'
                        country: USA
                    primary_payroll_admin:
                      first_name: Ian
                      last_name: Labadie
                      phone: 1-565-710-7559
                      email: louie.hessel7757869450111547@zemlak.biz
    parameters:
      - schema:
          type: string
        name: company_id
        in: path
        description: The ID of the company
        required: true
  /oauth/token:
    post:
      summary: 'Manage tokens [not done]'
      responses: {}
      operationId: post-oauth-token
      tags:
        - Auth
  '/v1/companies/{company_id}/employees':
    parameters:
      - schema:
          type: string
        name: company_id
        in: path
        required: true
        description: The ID of the company
    get:
      summary: 'Get employees of a company [not done]'
      tags:
        - Employee
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                uniqueItems: true
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: The unique identifier of the employee in Gusto.
                      readOnly: true
                    first_name:
                      type: string
                      readOnly: true
                    middle_initial:
                      type:
                        - string
                        - 'null'
                      readOnly: true
                    last_name:
                      type: string
                      readOnly: true
                    email:
                      type:
                        - string
                        - 'null'
                      description: The email address of the employee. This is provided to support syncing users between our system and yours. You may not use this email address for any other purpose (e.g. marketing).
                      readOnly: true
                    company_id:
                      type: number
                      description: The ID of the company the employee is employed by in Gusto.
                      readOnly: true
                    manager_id:
                      type:
                        - number
                        - 'null'
                      description: The ID of the employee's manager in Gusto.
                      readOnly: true
                    version:
                      type: string
                      description: The current version of the employee. See the versioning guide for details using this field.
                      readOnly: true
                    department:
                      type:
                        - string
                        - 'null'
                      description: The employee's department in the company.
                      readOnly: true
                    terminated:
                      type: boolean
                      description: Whether the employee is terminated.
                    two_percent_shareholder:
                      type: boolean
                      description: Whether the employee is a two percent shareholder of the company. This field only applies to companies with an S-Corp entity type.
                    onboarded:
                      type: boolean
                      description: Whether the employee has completed onboarding.
                    jobs:
                      type: array
                      uniqueItems: true
                      minItems: 1
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                          version:
                            type: string
                            minLength: 1
                          employee_id:
                            type: number
                          current_compensation_id:
                            type: number
                          payment_unit:
                            type: string
                            minLength: 1
                          primary:
                            type: boolean
                          title:
                            type: string
                            minLength: 1
                          compensations:
                            type: array
                            uniqueItems: true
                            minItems: 1
                            items:
                              type: object
                              properties:
                                id:
                                  type: number
                                version:
                                  type: string
                                  minLength: 1
                                payment_unit:
                                  type: string
                                  minLength: 1
                                flsa_status:
                                  type: string
                                  minLength: 1
                                job_id:
                                  type: number
                                effective_date:
                                  type: string
                                  minLength: 1
                                rate:
                                  type: string
                                  minLength: 1
                              required:
                                - id
                                - version
                                - payment_unit
                                - flsa_status
                                - job_id
                                - effective_date
                                - rate
                          rate:
                            type: string
                            minLength: 1
                          hire_date:
                            type: string
                            minLength: 1
                          location_id:
                            type: number
                          location:
                            type: object
                            properties:
                              id:
                                type: number
                              street_1:
                                type: string
                                minLength: 1
                              street_2:
                                type: string
                                minLength: 1
                              city:
                                type: string
                                minLength: 1
                              state:
                                type: string
                                minLength: 1
                              zip:
                                type: string
                                minLength: 1
                              country:
                                type: string
                                minLength: 1
                              inactive:
                                type: boolean
                            required:
                              - id
                              - street_1
                              - street_2
                              - city
                              - state
                              - zip
                              - country
                              - inactive
                        required:
                          - id
                          - version
                          - employee_id
                          - current_compensation_id
                          - payment_unit
                          - primary
                          - title
                          - rate
                          - hire_date
                          - location_id
                    eligible_paid_time_off:
                      type: array
                      uniqueItems: true
                      minItems: 1
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            minLength: 1
                          accrual_unit:
                            type: string
                            minLength: 1
                          accrual_rate:
                            type: string
                            minLength: 1
                          accrual_period:
                            type: string
                            minLength: 1
                          accrual_balance:
                            type: string
                            minLength: 1
                          maximum_accrual_balance:
                            type: string
                            minLength: 1
                          paid_at_termination:
                            type: boolean
                        required:
                          - name
                          - accrual_unit
                          - accrual_rate
                          - accrual_period
                          - accrual_balance
                          - maximum_accrual_balance
                          - paid_at_termination
                    terminations:
                      type: array
                      items:
                        type: object
                    home_address:
                      $ref: '#/components/schemas/Location'
                    garnishments:
                      type: array
                      items:
                        type: object
                    date_of_birth:
                      type:
                        - string
                        - 'null'
                      readOnly: true
                    ssn:
                      type: string
                      description: Deprecated. This field always returns an empty string.
                      readOnly: true
                    phone:
                      type: string
                      readOnly: true
                    preferred_first_name:
                      type: string
                      description: ''
                      readOnly: true
                    work_email:
                      type:
                        - string
                        - 'null'
                      description: The work email address of the employee. This is provided to support syncing users between our system and yours. You may not use this email address for any other purpose (e.g. marketing).
                      readOnly: true
                  required:
                    - jobs
                    - eligible_paid_time_off
                    - terminations
                    - garnishments
                  readOnly: true
                readOnly: true
              examples:
                Example:
                  value:
                    - id: 0
                      first_name: string
                      middle_initial: null
                      last_name: string
                      email: string
                      company_id: 0
                      manager_id: 0
                      version: string
                      department: null
                      terminated: true
                      two_percent_shareholder: true
                      onboarded: true
                      jobs:
                        - id: 0
                          version: string
                          employee_id: 0
                          current_compensation_id: 0
                          payment_unit: string
                          primary: true
                          title: string
                          compensations:
                            - id: 0
                              version: string
                              payment_unit: string
                              flsa_status: string
                              job_id: 0
                              effective_date: string
                              rate: string
                          rate: string
                          hire_date: string
                          location_id: 0
                          location:
                            id: 0
                            street_1: string
                            street_2: string
                            city: string
                            state: string
                            zip: string
                            country: string
                            inactive: true
                      eligible_paid_time_off:
                        - name: string
                          accrual_unit: string
                          accrual_rate: string
                          accrual_period: string
                          accrual_balance: string
                          maximum_accrual_balance: string
                          paid_at_termination: true
                      terminations:
                        - {}
                      home_address:
                        version: string
                        employee_id: 0
                        street_1: string
                        street_2: string
                        city: string
                        state: string
                        zip: string
                        country: string
                        active: true
                      garnishments:
                        - {}
                      date_of_birth: string
                      ssn: string
                      phone: string
                      preferred_first_name: string
                      work_email: null
      operationId: get-v1-companies-company_id-employees
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: The access token
          required: true
      description: 'Retrieve all of the employees, onboarding, active and terminated, for a given company.'
components:
  schemas:
    Location:
      description: The representation of an address in Gusto.
      type: object
      x-examples:
        Company Location:
          company_id: 7756341740978008
          version: 7d9753112507b9dda4fb97910f39b06e
          phone_number: '5825710808'
          id: 7757727716657803
          street_1: 412 Kiera Stravenue
          street_2: Suite 391
          city: San Francisco
          state: CA
          zip: '94107'
          country: USA
          active: true
      properties:
        id:
          type: integer
          description: The unique identifier of the location in Gusto.
          readOnly: true
        version:
          type: string
          description: The current version of the object. See the versioning guide for information on how to use this field.
          readOnly: true
        company_id:
          type: integer
          description: The ID for the company to which the location belongs. Only included if the location belongs to a company.
          readOnly: true
        employee_id:
          type: integer
          description: The ID for the employee to which the location belongs. Only included if the location belongs to an employee.
          readOnly: true
        phone_number:
          type: string
          readOnly: false
          description: The phone number for the location. Required for company locations. Optional for employee locations.
        street_1:
          type: string
          readOnly: false
        street_2:
          type:
            - string
            - 'null'
          readOnly: false
        city:
          type: string
          readOnly: false
        state:
          type: string
          readOnly: false
        zip:
          type: string
          readOnly: false
        country:
          type: string
          readOnly: false
          default: USA
        active:
          type: boolean
          description: 'The status of the location. Inactive locations have been deleted, but may still have historical data associated with them.'
          readOnly: true
    Employee:
      title: Employee
      type: object
      description: The representation of an employee in Gusto.
      properties:
        id:
          type: number
          description: The unique identifier of the employee in Gusto.
          readOnly: true
        first_name:
          type: string
        middle_initial:
          type:
            - string
            - 'null'
        last_name:
          type: string
        email:
          type:
            - string
            - 'null'
          description: The email address of the employee. This is provided to support syncing users between our system and yours. You may not use this email address for any other purpose (e.g. marketing).
        company_id:
          type: number
          description: The ID of the company the employee is employed by in Gusto.
          readOnly: true
        manager_id:
          type:
            - number
            - 'null'
          description: The ID of the employee's manager in Gusto.
          readOnly: true
        version:
          type: string
          description: The current version of the employee. See the versioning guide for details using this field.
          readOnly: true
        department:
          type:
            - string
            - 'null'
          description: The employee's department in the company.
          readOnly: true
        terminated:
          type: boolean
          description: Whether the employee is terminated.
          readOnly: true
        two_percent_shareholder:
          type: boolean
          description: Whether the employee is a two percent shareholder of the company. This field only applies to companies with an S-Corp entity type.
        onboarded:
          type: boolean
          description: Whether the employee has completed onboarding.
          readOnly: true
        jobs:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/Job'
        eligible_paid_time_off:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Paid-Time-Off'
        terminations:
          type: array
          items:
            $ref: '#/components/schemas/Termination'
        home_address:
          $ref: '#/components/schemas/Location'
        garnishments:
          type: array
          items:
            $ref: '#/components/schemas/Garnishment'
        date_of_birth:
          type:
            - string
            - 'null'
          readOnly: true
        ssn:
          type: string
          description: Deprecated. This field always returns an empty string.
        phone:
          type: string
        preferred_first_name:
          type: string
          description: ''
        work_email:
          type:
            - string
            - 'null'
          description: The work email address of the employee. This is provided to support syncing users between our system and yours. You may not use this email address for any other purpose (e.g. marketing).
      readOnly: true
      x-examples:
        Example:
          id: 0
          first_name: string
          middle_initial: null
          last_name: string
          email: null
          company_id: 0
          manager_id: null
          version: string
          department: null
          terminated: true
          two_percent_shareholder: true
          onboarded: true
          jobs:
            - id: 0
              version: string
              employee_id: 0
              location_id: 0
              location:
                id: 0
                street_1: string
                street_2: string
                city: string
                state: string
                zip: string
                country: string
                inactive: true
              hire_date: string
              title: null
              primary: true
              rate: string
              payment_unit: string
              current_compensation_id: 0
              compensations:
                - id: 0
                  version: string
                  job_id: 0
                  rate: string
                  payment_unit: Hour
                  flsa_status: Exempt
                  effective_date: string
          eligible_paid_time_off:
            - name: string
              accrual_unit: Hour
              accrual_rate: string
              accrual_period: Year
              accrual_balance: string
              maximum_accrual_balance: null
              paid_at_termination: true
          terminations:
            - id: 0
              version: string
              employee_id: 0
              active: true
              effective_date: string
              run_termination_payroll: true
          home_address:
            id: 0
            version: string
            company_id: 0
            employee_id: 0
            phone_number: string
            street_1: string
            street_2: null
            city: string
            state: string
            zip: string
            country: USA
            active: true
          garnishments:
            - id: 0
              version: string
              employee_id: 0
              active: true
              amount: 0
              description: string
              court_ordered: true
              times: null
              recurring: false
              annual_maximum: null
              pay_period_maximum: null
              deduct_as_percentage: false
          date_of_birth: null
          ssn: string
          phone: string
          preferred_first_name: string
          work_email: null
    Paid-Time-Off:
      description: The representation of paid time off in Gusto.
      type: object
      properties:
        name:
          type: string
          description: The name of the paid time off type.
          readOnly: true
        accrual_unit:
          type: string
          example: Hour
          description: The unit the PTO type is accrued in.
          readOnly: true
        accrual_rate:
          type: string
          description: The number of accrual units accrued per accrual period.
          readOnly: true
        accrual_period:
          type: string
          example: Year
          description: The frequency at which the PTO type is accrued.
          readOnly: true
        accrual_balance:
          type: string
          description: The number of accrual units accrued.
          readOnly: true
        maximum_accrual_balance:
          type:
            - string
            - 'null'
          description: The maximum number of accrual units allowed. A null value signifies no maximum.
          readOnly: true
        paid_at_termination:
          type: boolean
          description: Whether the accrual balance is paid to the employee upon termination.
          readOnly: true
      x-examples:
        Example:
          name: Sick Hours
          accrual_unit: Hour
          accrual_rate: '208.0'
          accrual_period: Year
          accrual_balance: '64.0'
          maximum_accrual_balance: '240.0'
          paid_at_termination: false
    Garnishment:
      description: 'Garnishments, or employee deductions, are fixed amounts or percentages deducted from an employeeâ€™s pay. They can be deducted a specific number of times or on a recurring basis. Garnishments can also have maximum deductions on a yearly or per-pay-period bases. Common uses for garnishments are court-ordered payments for child support or back taxes. Some companies provide loans to their employees that are repaid via garnishments.'
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the garnishment in Gusto.
          readOnly: true
        version:
          type: string
          description: The current version of the object. See the versioning guide for information on how to use this field.
          readOnly: true
        employee_id:
          type: integer
          description: The ID of the employee to which this garnishment belongs.
          readOnly: true
        active:
          type: boolean
          default: true
          description: Whether or not this garnishment is currently active.
        amount:
          type: number
          format: float
          readOnly: false
          description: The amount of the garnishment. Either a percentage or a fixed dollar amount.
        description:
          type: string
          readOnly: false
          description: The description of the garnishment.
        court_ordered:
          type: boolean
          readOnly: false
          description: Whether the garnishment is court ordered.
        times:
          type:
            - integer
            - 'null'
          readOnly: false
          default: null
          description: The number of times to apply the garnisment. Ignored if recurring is true.
        recurring:
          type: boolean
          readOnly: false
          default: false
          description: Whether the garnishment should recur indefinitely.
        annual_maximum:
          type:
            - number
            - 'null'
          format: float
          readOnly: false
          default: null
          description: The maximum deduction per annum. A null value indicates no maximum.
        pay_period_maximum:
          type:
            - number
            - 'null'
          format: float
          default: null
          description: The maximum deduction per pay period. A null value indicates no maximum.
        deduct_as_percentage:
          type: boolean
          readOnly: false
          default: false
          description: Whether the amount should be treated as a percentage to be deducted per pay period.
      x-examples:
        Example:
          id: 1363316538400333
          version: 52b7c567242cb7452e89ba2bc02cb476
          employee_id: 8964216891236743
          active: true
          amount: '8.00'
          description: Company loan to employee
          court_ordered: false
          times: 5
          recurring: false
          annual_maximum: null
          pay_period_maximum: '100.00'
          deduct_as_percentage: true
    Termination:
      type: object
      description: The representation of a termination in Gusto.
      properties:
        id:
          type: integer
          description: The unique identifier of the termination in Gusto.
          readOnly: true
        version:
          type: string
          description: The current version of the object. See the versioning guide for information on how to use this field.
          readOnly: true
        employee_id:
          type: integer
          description: The ID of the employee to which this termination is attached.
          readOnly: true
        active:
          type: boolean
          description: Whether the employee's termination has gone into effect.
          readOnly: true
        effective_date:
          type: string
          readOnly: false
          description: The employee's last day of work.
        run_termination_payroll:
          type: boolean
          readOnly: false
          description: 'If true, the employee should recieve their final wages via an offcycle payroll. If false, they should recieve their final wages on their current pay schedule.'
      x-examples:
        example-1:
          id: 891238902131212
          version: d487dd0b55dfcacdd920ccbdaeafa351
          active: true
          effective_date: '2020-03-10'
          run_termination_payroll: false
    Compensation:
      type: object
      description: The representation of compensation in Gusto.
      properties:
        id:
          type: integer
          description: The unique identifier of the compensation in Gusto.
          readOnly: true
        version:
          type: string
          description: The current version of the object. See the versioning guide for information on how to use this field.
          readOnly: true
        job_id:
          type: integer
          description: The ID of the job to which the compensation belongs.
          readOnly: true
        rate:
          type: string
          readOnly: false
          description: The dollar amount paid per payment unit.
        payment_unit:
          type: string
          readOnly: false
          description: 'The unit accompanying the compensation rate. If the employee is an owner, rate should be ''Paycheck''.'
          enum:
            - Hour
            - Week
            - Month
            - Year
            - Paycheck
        flsa_status:
          type: string
          readOnly: false
          description: 'The FLSA status for this compensation. Salaried (''Exempt'') employees are paid a fixed salary every pay period. Salaried with overtime (''Salaried Nonexempt'') employees are paid a fixed salary every pay period, and receive overtime pay when applicable. Hourly (''Nonexempt'') employees are paid for the hours they work, and receive overtime pay when applicable. Owners (''Owner'') are employees that own at least twenty percent of the company. '
          enum:
            - Exempt
            - Salaried Nonexempt
            - Nonexempt
            - Owner
        effective_date:
          type: string
          readOnly: false
          description: 'The effective date for this compensation. For the first compensation, this defaults to the job''s hire date.'
      x-examples:
        Example:
          id: 1363316536327004
          version: 98jr3289h3298hr9329gf9egskt3kagri32qqgiqe3872
          job_id: 1123581321345589
          rate: '70.00'
          payment_unit: Hour
          flsa_status: Nonexempt
          effective_date: '2020-12-11'
    Job:
      title: Job
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the job in Gusto.
          readOnly: true
        version:
          type: string
          description: The current version of the object. See the versioning guide for information on how to use this field.
          readOnly: true
        employee_id:
          type: integer
          description: The ID of the employee to which the job belongs.
          readOnly: true
        location_id:
          type: integer
          readOnly: false
          description: The ID of the job's work location.
        location:
          type: object
          properties:
            id:
              type: number
              readOnly: true
            street_1:
              type: string
              readOnly: true
            street_2:
              type: string
              readOnly: true
            city:
              type: string
              readOnly: true
            state:
              type: string
              readOnly: true
            zip:
              type: string
              readOnly: true
            country:
              type: string
              readOnly: true
            inactive:
              type: boolean
              readOnly: true
              description: Whether the location of the job is active.
        hire_date:
          type: string
          readOnly: false
          description: The date when the employee was hired for the job.
        title:
          type: string
          readOnly: false
          default: null
          description: The title for the job.
        primary:
          type: boolean
          description: Whether this is the employeeâ€™s primary job. The value will be set to true unless an existing job exists for the employee.
          readOnly: true
        rate:
          type: string
          description: The current compensation rate of the job.
          readOnly: true
        payment_unit:
          type: string
          description: The payment unit of the current compensation for the job.
          readOnly: true
        current_compensation_id:
          type: integer
          description: The ID for the current compensation of the job.
          readOnly: true
        compensations:
          type: array
          items:
            $ref: '#/components/schemas/Compensation'
          readOnly: true
      description: The representation of a job in Gusto.
      x-examples:
        Example:
          id: 7757869441038000
          version: d0e719137f89ca3dd334dd4cc248ffbb
          employee_id: 7757869432666661
          current_compensation_id: 7757869444844981
          payment_unit: Year
          primary: true
          title: Account Director
          compensations:
            - id: 7757869444844981
              version: 994b75511d1debac5d7e2ddeae13679f
              payment_unit: Year
              flsa_status: Exempt
              job_id: 7757869441038000
              effective_date: '2021-01-20'
              rate: '78000.00'
          rate: '78000.00'
          hire_date: '2020-01-20'
          location_id: 7757727716657803
          location:
            id: 7757727716657803
            street_1: 412 Kiera Stravenue
            street_2: Suite 391
            city: San Francisco
            state: CA
            zip: '94107'
            country: USA
            inactive: false
  securitySchemes: {}
